name: pr-validation

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main]
  workflow_dispatch:

jobs:
  pr-validation:
    uses: salesforcecli/github-workflows/.github/workflows/validatePR.yml@main
